[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/about"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/releases/:project-name"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/releases"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/conversations/:title"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/conversations"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/resources"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/contact"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/suggestions"
to = "/index.html"
status = 200
force = false

# Social media redirect
[[redirects]]
from = "/twitter"
to = "https://twitter.com/BrainMeToo"
status = 301

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/brainmetoo/"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/bettermetoo"
status = 301

[[redirects]]
from = "/medium"
to = "https://medium.com/better-me-too"
status = 301

# This is needed because we're using relative path LOL
[[redirects]]
from = "/conversations/dist/*"
to = "/dist/:splat"
status = 200
force = true

[[redirects]]
from = "/releases/dist/*"
to = "/dist/:splat"
status = 200
force = true
